languge: java
install: true

os: linux
dist: trusty
jdk: openjdk8

notification:
    email: oraedoa@gmail.com

before_script:
    - echo "Before Script"

# 프로젝트 빌드의 전체적인 상황을 확인할 수 있도록 설정하는 옵션 (--scan)
script:
    - echo "Hello World"
    - ./gradlew build

after_script:
    - echo "After Scrpt"

after_success:
    - echo "After Success"
